### PR TITLE
feat: format message in stream response

### PR DESCRIPTION
**Pull request by Caulm**
Solve #24. If any incorrect formatting is found, please let me know.

The Cli preview image in readme may need to be updated after this commit. But I'm unable to take a screenshot due to a problem with overlapping text. So please help me update it if you have time.

### CODE REVIEW

**Comment by neon-sunset** [comment]
Please try to avoid storing all responses to a List - they just have duplicated messages like "Hello", "Hello this is", "Hello This is Bing", etc. combined with a lot of other irrelevant data so these are discarded intentionally and we only slice the difference between lengths and pass exactly that short segment to response stream.

The way it currently works:
```mermaid
sequenceDiagram
    Client->>Client: Register "update" client method callback
    Client->>Server: Send "chat" request with streaming response
    Server->>Client: Push "update" ChatResponse messages
    Client->>Client: Bind to the first "update" messageId and start streaming text segments
    Server-->>Client: Complete pushing "update" ChatResponse messages
    Server-->>Client: Send "chat" response aka finalized response over response stream
    Client->>Client: Match "chat" response against previously bound messageId and stream last segment if any
```

You may want to alter the logic to something like:
- Reformat `[^1^]` in streamed text segments to e.g. `[1]` or anything you think is reasonable
- On finalized response if matched against `messageId`, review all source attributions and adaptive cards and append them at the end in the form of the very last text segment (or maybe multiple if you would like to split, let's say, source attributions and cards if you think it's better)

This would allow us to avoid complex matching logic and wasting memory on storing intermediate state and format the remainder of response one-shot.

In order to consolidate the above logic with `AskAsync`, you will need to collect text segments from `StreamAsync` into a `StringBuilder` and then `.ToString()` it on stream completion.

**Comment by Caulm** [comment]
Thanks for advice! :) I understand the structure of the response stream and the communication between servers, as I have also tested some scenarios myself.

Here are my considerations. I wanted to save previous messages because there may be multiple chat messages with different `messageIds` that make up the final answer. In some cases, Bing may overwrite a message, causing the messageId to change. So I hope all received messages can be joined, rather than just parsing the first chat message. One example is like this.


How about this to avoid excessive memory usage?

- Cache only one previous message object. When receiving the next message, compare the messageId with the previous one.
- If equal, output the appending part, without source attributions; otherwise, output the remaining part of the previous message, containing source attributions, and the beginning of the next message.
- Change the parser class to a builder class and implement the ability to cache messages. `StreamAsync` needs to pass one latest response to the builder and get an appending string from it.

By the way, Transforming `[^1^]` to `[1]` maybe a UI matter as I think, so it should be done in Cli? The original format should be preserved here.

**Comment by Caulm** [comment]
Need some work to recreate a PR

**Comment by neon-sunset** [comment]
@Caulm I didn't realize you can actually make it respond in multiple messages.

As you said, caching previous message object + outputting attributions/cards when id changes seems like the way to go, this makes sense and would be fairly efficient. I think `MessageBuilder` may need to change to e.g.`AttributionsFormatter` which only deals with producing a string with formatted attributions and cards, since the streaming logic will need only a few more conditionals to work as described. Also yes, formatting attribution marks seems like something for the library consumers (i.e. CLI) to deal with, especially since it uses special unicode characters to highlight those.

Do you plan to continue working on the change?

**Pull request closed without merging**
